name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (UTC)
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
          days-before-stale: 30
          days-before-close: 7
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security'
          close-issue-message: 'Closing this issue due to inactivity.'
          close-pr-message: 'Closing this pull request due to inactivity.'
